### ISSUE TITLE
Insertion fails when adding (maxEntries + 2) empty bboxes

### ISSUE THREAD

**Issue by quentin-ol** [mourner/rbush#40]
Inserting (maxEntries + 2)  empty bboxes in a rbush fails with:
>
"TypeError: Cannot read property 'leaf' of undefined
    at Object.rbush._chooseSubtree (https://rawgit.com/mourner/rbush/master/rbush.js:279:21)
    at Object.rbush._insert (https://rawgit.com/mourner/rbush/master/rbush.js:316:25)
    at Object.rbush.insert 

To trace down the error, I put together this JSBin: http://jsbin.com/bidaqov/15/edit?js,console
It shows that at https://github.com/mourner/rbush/blob/master/rbush.js#L286 ,
the function `enlargedArea` returns `NaN`. Because of this, none of the if/else-if statements are matched and `targetNode` is never initialized. 

The next `while(true)` loop iteration fails when accessing `node.leaf`

**Comment by quentin-ol** [comment]
JSBin with PR: http://jsbin.com/bidaqov/16/edit?html,js,console .
Notice that it no longer fails.
